num_sorte = [4, 6, 10 , 19, 11, 7]
print(num_sorte)
amigos = ["jeff", "bruna", "rob", "poe", "alex"]
print(amigos)
amigos.extend(num_sorte)
print(amigos)
amigos.append("jorge")
print(amigos)
amigos.insert(4, "albert")
print(amigos)
amigos.remove("albert")
print(amigos)
#amigos.clear()
print(amigos)
#amigos.pop()
print(amigos)
#print(amigos.index("maximilian"))
print(amigos.index("jorge"))
amigos.sort()
print(amigos)